### PR TITLE
Pronounce better

### PR DESCRIPTION
**Pull request by freben**

### CODE REVIEW

**Comment by rouzwawi** [comment]
There's a weird `a-yay` at the end, can you make it sound more swedish?

**Comment by freben** [comment]
@rouzwawi Alright, updated with 24% more swedishness

**Comment by rouzwawi** [comment]
@freben `leeteh` sounds good, but there's an extra word in the end now.

**Comment by freben** [comment]
@rouzwawi I'll add the micropayment option for retaining the extra word in a follow-up PR

**Comment by freben** [comment]
@rouzwawi ping

**Comment by rouzwawi** [comment]
Thank you for your contribution. A certificate of participation is en route to your residence pod.

**Comment by freben** [comment]
I deleted the branch post-merge too. We're not savages.

**Pull request merged**
